### ISSUE TITLE
Unhandled AxiosError

### ISSUE THREAD

**Issue by arjunmehta** [runpod/js-sdk#6]
@DireLines 

```
AxiosError: socket hang up
    at AxiosError.from (file:///workspace/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///workspace/node_modules/axios/lib/adapters/http.js:610:25)
    at RedirectableRequest.emit (node:events:519:28)
    at eventHandlers.<computed> (/workspace/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketCloseListener (node:_http_client:473:11)
    at TLSSocket.emit (node:events:531:35)
    at node:net:338:12
    at TCP.done (node:_tls_wrap:657:7)
    at Axios.request (file:///workspace/node_modules/axios/lib/core/Axios.js:45:41) {
```

In production on an App Engine instance if that helps. The error shows up randomly.

I see that PR #4  from 3 months ago migrated away from Axios. But it doesn't seem to have been published to npm.

**Comment by zackmckennarunpod** [comment]
A new release has been published, closing the issue!
